# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - main

jobs:

  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'

    - name: Check Java version
      run: java -version
      
    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload artifact for Docker
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact from Maven
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Logging in
      run: docker login ghcr.io -u lessercodes -p ${{ github.token }}

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/lessercodes/cubix/cloudnative/demo:actions

    - name: Publish Docker image
      run: docker push ghcr.io/lessercodes/cubix/cloudnative/demo:actions